#coding: utf-8
from django.db import models
from Languages.models import Languages
from SQL2Django import uppercaseAbbrInDatabase

a=Languages (abbr= 'aa' , name= 'Afar')
a.save()
a=Languages (abbr= 'ab' , name= 'Abkhazian')
a.save()
a=Languages (abbr= 'ae' , name= 'Avestan')
a.save()
a=Languages (abbr= 'af' , name= 'Afrikaans')
a.save()
a=Languages (abbr= 'ak' , name= 'Akan')
a.save()
a=Languages (abbr= 'am' , name= 'Amharic')
a.save()
a=Languages (abbr= 'an' , name= 'Aragonese')
a.save()
a=Languages (abbr= 'ar' , name= 'Arabic')
a.save()
a=Languages (abbr= 'as' , name= 'Assamese')
a.save()
a=Languages (abbr= 'av' , name= 'Avaric')
a.save()
a=Languages (abbr= 'ay' , name= 'Aymara')
a.save()
a=Languages (abbr= 'az' , name= 'Azerbaijani')
a.save()
a=Languages (abbr= 'ba' , name= 'Bashkir')
a.save()
a=Languages (abbr= 'be' , name= 'Belarusian')
a.save()
a=Languages (abbr= 'bg' , name= 'Bulgarian')
a.save()
a=Languages (abbr= 'bh' , name= 'Bihari languages')
a.save()
a=Languages (abbr= 'bi' , name= 'Bislama')
a.save()
a=Languages (abbr= 'bm' , name= 'Bambara')
a.save()
a=Languages (abbr= 'bn' , name= 'Bengali')
a.save()
a=Languages (abbr= 'bo' , name= 'Tibetan')
a.save()
a=Languages (abbr= 'br' , name= 'Breton')
a.save()
a=Languages (abbr= 'bs' , name= 'Bosnian')
a.save()
a=Languages (abbr= 'ca' , name= 'Catalan')
a.save()
a=Languages (abbr= 'ce' , name= 'Chechen')
a.save()
a=Languages (abbr= 'ch' , name= 'Chamorro')
a.save()
a=Languages (abbr= 'co' , name= 'Corsican')
a.save()
a=Languages (abbr= 'cr' , name= 'Cree')
a.save()
a=Languages (abbr= 'cs' , name= 'Czech')
a.save()
a=Languages (abbr= 'cu' , name= 'Church Slavic')
a.save()
a=Languages (abbr= 'cv' , name= 'Chuvash')
a.save()
a=Languages (abbr= 'cy' , name= 'Welsh')
a.save()
a=Languages (abbr= 'da' , name= 'Danish')
a.save()
a=Languages (abbr= 'de' , name= 'German')
a.save()
a=Languages (abbr= 'dv' , name= 'Divehi')
a.save()
a=Languages (abbr= 'dz' , name= 'Dzongkha')
a.save()
a=Languages (abbr= 'ee' , name= 'Ewe')
a.save()
a=Languages (abbr= 'el' , name= 'Greek, Modern (1453)')
a.save()
a=Languages (abbr= 'en' , name= 'English')
a.save()
a=Languages (abbr= 'eo' , name= 'Esperanto')
a.save()
a=Languages (abbr= 'es' , name= 'Spanish')
a.save()
a=Languages (abbr= 'et' , name= 'Estonian')
a.save()
a=Languages (abbr= 'eu' , name= 'Basque')
a.save()
a=Languages (abbr= 'fa' , name= 'Persian')
a.save()
a=Languages (abbr= 'ff' , name= 'Fulah')
a.save()
a=Languages (abbr= 'fi' , name= 'Finnish')
a.save()
a=Languages (abbr= 'fj' , name= 'Fijian')
a.save()
a=Languages (abbr= 'fo' , name= 'Faroese')
a.save()
a=Languages (abbr= 'fr' , name= 'French')
a.save()
a=Languages (abbr= 'fy' , name= 'Western Frisian')
a.save()
a=Languages (abbr= 'ga' , name= 'Irish')
a.save()
a=Languages (abbr= 'gd' , name= 'Gaelic')
a.save()
a=Languages (abbr= 'gl' , name= 'Galician')
a.save()
a=Languages (abbr= 'gn' , name= 'Guarani')
a.save()
a=Languages (abbr= 'gu' , name= 'Gujarati')
a.save()
a=Languages (abbr= 'gv' , name= 'Manx')
a.save()
a=Languages (abbr= 'ha' , name= 'Hausa')
a.save()
a=Languages (abbr= 'he' , name= 'Hebrew')
a.save()
a=Languages (abbr= 'hi' , name= 'Hindi')
a.save()
a=Languages (abbr= 'ho' , name= 'Hiri Motu')
a.save()
a=Languages (abbr= 'hr' , name= 'Croatian')
a.save()
a=Languages (abbr= 'ht' , name= 'Haitian')
a.save()
a=Languages (abbr= 'hu' , name= 'Hungarian')
a.save()
a=Languages (abbr= 'hy' , name= 'Armenian')
a.save()
a=Languages (abbr= 'hz' , name= 'Herero')
a.save()
a=Languages (abbr= 'ia' , name= 'Interlingua (International Auxiliary Language Association)')
a.save()
a=Languages (abbr= 'id' , name= 'Indonesian')
a.save()
a=Languages (abbr= 'ie' , name= 'Interlingue')
a.save()
a=Languages (abbr= 'ig' , name= 'Igbo')
a.save()
a=Languages (abbr= 'ii' , name= 'Sichuan Yi')
a.save()
a=Languages (abbr= 'ik' , name= 'Inupiaq')
a.save()
a=Languages (abbr= 'io' , name= 'Ido')
a.save()
a=Languages (abbr= 'is' , name= 'Icelandic')
a.save()
a=Languages (abbr= 'it' , name= 'Italian')
a.save()
a=Languages (abbr= 'iu' , name= 'Inuktitut')
a.save()
a=Languages (abbr= 'ja' , name= 'Japanese')
a.save()
a=Languages (abbr= 'jv' , name= 'Javanese')
a.save()
a=Languages (abbr= 'ka' , name= 'Georgian')
a.save()
a=Languages (abbr= 'kg' , name= 'Kongo')
a.save()
a=Languages (abbr= 'ki' , name= 'Kikuyu')
a.save()
a=Languages (abbr= 'kj' , name= 'Kuanyama')
a.save()
a=Languages (abbr= 'kk' , name= 'Kazakh')
a.save()
a=Languages (abbr= 'kl' , name= 'Kalaallisut')
a.save()
a=Languages (abbr= 'km' , name= 'Central Khmer')
a.save()
a=Languages (abbr= 'kn' , name= 'Kannada')
a.save()
a=Languages (abbr= 'ko' , name= 'Korean')
a.save()
a=Languages (abbr= 'kr' , name= 'Kanuri')
a.save()
a=Languages (abbr= 'ks' , name= 'Kashmiri')
a.save()
a=Languages (abbr= 'ku' , name= 'Kurdish')
a.save()
a=Languages (abbr= 'kv' , name= 'Komi')
a.save()
a=Languages (abbr= 'kw' , name= 'Cornish')
a.save()
a=Languages (abbr= 'ky' , name= 'Kirghiz')
a.save()
a=Languages (abbr= 'la' , name= 'Latin')
a.save()
a=Languages (abbr= 'lb' , name= 'Luxembourgish')
a.save()
a=Languages (abbr= 'lg' , name= 'Ganda')
a.save()
a=Languages (abbr= 'li' , name= 'Limburgan')
a.save()
a=Languages (abbr= 'ln' , name= 'Lingala')
a.save()
a=Languages (abbr= 'lo' , name= 'Lao')
a.save()
a=Languages (abbr= 'lt' , name= 'Lithuanian')
a.save()
a=Languages (abbr= 'lu' , name= 'Luba-Katanga')
a.save()
a=Languages (abbr= 'lv' , name= 'Latvian')
a.save()
a=Languages (abbr= 'mg' , name= 'Malagasy')
a.save()
a=Languages (abbr= 'mh' , name= 'Marshallese')
a.save()
a=Languages (abbr= 'mi' , name= 'Maori')
a.save()
a=Languages (abbr= 'mk' , name= 'Macedonian')
a.save()
a=Languages (abbr= 'ml' , name= 'Malayalam')
a.save()
a=Languages (abbr= 'mn' , name= 'Mongolian')
a.save()
a=Languages (abbr= 'mr' , name= 'Marathi')
a.save()
a=Languages (abbr= 'ms' , name= 'Malay')
a.save()
a=Languages (abbr= 'mt' , name= 'Maltese')
a.save()
a=Languages (abbr= 'my' , name= 'Burmese')
a.save()
a=Languages (abbr= 'na' , name= 'Nauru')
a.save()
a=Languages (abbr= 'nb' , name= 'Bokmål, Norwegian')
a.save()
a=Languages (abbr= 'nd' , name= 'Ndebele, North')
a.save()
a=Languages (abbr= 'ne' , name= 'Nepali')
a.save()
a=Languages (abbr= 'ng' , name= 'Ndonga')
a.save()
a=Languages (abbr= 'nl' , name= 'Dutch')
a.save()
a=Languages (abbr= 'nn' , name= 'Norwegian Nynorsk')
a.save()
a=Languages (abbr= 'no' , name= 'Norwegian')
a.save()
a=Languages (abbr= 'nr' , name= 'Ndebele, South')
a.save()
a=Languages (abbr= 'nv' , name= 'Navajo')
a.save()
a=Languages (abbr= 'ny' , name= 'Chichewa')
a.save()
a=Languages (abbr= 'oc' , name= 'Occitan (post 1500)')
a.save()
a=Languages (abbr= 'oj' , name= 'Ojibwa')
a.save()
a=Languages (abbr= 'om' , name= 'Oromo')
a.save()
a=Languages (abbr= 'or' , name= 'Oriya')
a.save()
a=Languages (abbr= 'os' , name= 'Ossetian')
a.save()
a=Languages (abbr= 'pa' , name= 'Panjabi')
a.save()
a=Languages (abbr= 'pi' , name= 'Pali')
a.save()
a=Languages (abbr= 'pl' , name= 'Polish')
a.save()
a=Languages (abbr= 'ps' , name= 'Pushto')
a.save()
a=Languages (abbr= 'pt' , name= 'Portuguese')
a.save()
a=Languages (abbr= 'qu' , name= 'Quechua')
a.save()
a=Languages (abbr= 'rm' , name= 'Romansh')
a.save()
a=Languages (abbr= 'rn' , name= 'Rundi')
a.save()
a=Languages (abbr= 'ro' , name= 'Romanian')
a.save()
a=Languages (abbr= 'ru' , name= 'Russian')
a.save()
a=Languages (abbr= 'rw' , name= 'Kinyarwanda')
a.save()
a=Languages (abbr= 'sa' , name= 'Sanskrit')
a.save()
a=Languages (abbr= 'sc' , name= 'Sardinian')
a.save()
a=Languages (abbr= 'sd' , name= 'Sindhi')
a.save()
a=Languages (abbr= 'se' , name= 'Northern Sami')
a.save()
a=Languages (abbr= 'sg' , name= 'Sango')
a.save()
a=Languages (abbr= 'si' , name= 'Sinhala')
a.save()
a=Languages (abbr= 'sk' , name= 'Slovak')
a.save()
a=Languages (abbr= 'sl' , name= 'Slovenian')
a.save()
a=Languages (abbr= 'sm' , name= 'Samoan')
a.save()
a=Languages (abbr= 'sn' , name= 'Shona')
a.save()
a=Languages (abbr= 'so' , name= 'Somali')
a.save()
a=Languages (abbr= 'sq' , name= 'Albanian')
a.save()
a=Languages (abbr= 'sr' , name= 'Serbian')
a.save()
a=Languages (abbr= 'ss' , name= 'Swati')
a.save()
a=Languages (abbr= 'st' , name= 'Sotho, Southern')
a.save()
a=Languages (abbr= 'su' , name= 'Sundanese')
a.save()
a=Languages (abbr= 'sv' , name= 'Swedish')
a.save()
a=Languages (abbr= 'sw' , name= 'Swahili')
a.save()
a=Languages (abbr= 'ta' , name= 'Tamil')
a.save()
a=Languages (abbr= 'te' , name= 'Telugu')
a.save()
a=Languages (abbr= 'tg' , name= 'Tajik')
a.save()
a=Languages (abbr= 'th' , name= 'Thai')
a.save()
a=Languages (abbr= 'ti' , name= 'Tigrinya')
a.save()
a=Languages (abbr= 'tk' , name= 'Turkmen')
a.save()
a=Languages (abbr= 'tl' , name= 'Tagalog')
a.save()
a=Languages (abbr= 'tn' , name= 'Tswana')
a.save()
a=Languages (abbr= 'to' , name= 'Tonga (Tonga Islands)')
a.save()
a=Languages (abbr= 'tr' , name= 'Turkish')
a.save()
a=Languages (abbr= 'ts' , name= 'Tsonga')
a.save()
a=Languages (abbr= 'tt' , name= 'Tatar')
a.save()
a=Languages (abbr= 'tw' , name= 'Twi')
a.save()
a=Languages (abbr= 'ty' , name= 'Tahitian')
a.save()
a=Languages (abbr= 'ug' , name= 'Uighur')
a.save()
a=Languages (abbr= 'uk' , name= 'Ukrainian')
a.save()
a=Languages (abbr= 'ur' , name= 'Urdu')
a.save()
a=Languages (abbr= 'uz' , name= 'Uzbek')
a.save()
a=Languages (abbr= 've' , name= 'Venda')
a.save()
a=Languages (abbr= 'vi' , name= 'Vietnamese')
a.save()
a=Languages (abbr= 'vo' , name= 'Volapük')
a.save()
a=Languages (abbr= 'wa' , name= 'Walloon')
a.save()
a=Languages (abbr= 'wo' , name= 'Wolof')
a.save()
a=Languages (abbr= 'xh' , name= 'Xhosa')
a.save()
a=Languages (abbr= 'yi' , name= 'Yiddish')
a.save()
a=Languages (abbr= 'yo' , name= 'Yoruba')
a.save()
a=Languages (abbr= 'za' , name= 'Zhuang')
a.save()
a=Languages (abbr= 'zh' , name= 'Chinese')
a.save()
a=Languages (abbr= 'zu' , name= 'Zulu')
a.save()

uppercaseAbbrInDatabase()