INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('aa' , 'Afar ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('ab' , 'Abkhazian ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('ae' , 'Avestan ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('af' , 'Afrikaans ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('ak' , 'Akan ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('am' , 'Amharic ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('an' , 'Aragonese ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('ar' , 'Arabic ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('as' , 'Assamese ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('av' , 'Avaric ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('ay' , 'Aymara ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('az' , 'Azerbaijani ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('ba' , 'Bashkir ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('be' , 'Belarusian ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('bg' , 'Bulgarian ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('bh' , 'Bihari languages ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('bi' , 'Bislama ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('bm' , 'Bambara ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('bn' , 'Bengali ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('bo' , 'Tibetan ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('br' , 'Breton ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('bs' , 'Bosnian ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('ca' , 'Catalan')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('ce' , 'Chechen ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('ch' , 'Chamorro ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('co' , 'Corsican ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('cr' , 'Cree ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('cs' , 'Czech ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('cu' , 'Church Slavic')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('cv' , 'Chuvash ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('cy' , 'Welsh ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('da' , 'Danish ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('de' , 'German ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('dv' , 'Divehi')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('dz' , 'Dzongkha ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('ee' , 'Ewe ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('el' , 'Greek, Modern (\'1453-\') ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('en' , 'English ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('eo' , 'Esperanto ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('es' , 'Spanish')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('et' , 'Estonian ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('eu' , 'Basque ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('fa' , 'Persian ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('ff' , 'Fulah ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('fi' , 'Finnish ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('fj' , 'Fijian ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('fo' , 'Faroese ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('fr' , 'French ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('fy' , 'Western Frisian ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('ga' , 'Irish ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('gd' , 'Gaelic')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('gl' , 'Galician ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('gn' , 'Guarani ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('gu' , 'Gujarati ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('gv' , 'Manx ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('ha' , 'Hausa ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('he' , 'Hebrew ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('hi' , 'Hindi ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('ho' , 'Hiri Motu ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('hr' , 'Croatian ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('ht' , 'Haitian')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('hu' , 'Hungarian ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('hy' , 'Armenian ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('hz' , 'Herero ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('ia' , 'Interlingua (\'International Auxiliary Language Association\') ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('id' , 'Indonesian ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('ie' , 'Interlingue')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('ig' , 'Igbo ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('ii' , 'Sichuan Yi')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('ik' , 'Inupiaq ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('io' , 'Ido ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('is' , 'Icelandic ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('ISO 639-1 Code' , 'English name of Language ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('it' , 'Italian ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('iu' , 'Inuktitut ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('ja' , 'Japanese ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('jv' , 'Javanese ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('ka' , 'Georgian ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('kg' , 'Kongo ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('ki' , 'Kikuyu')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('kj' , 'Kuanyama')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('kk' , 'Kazakh ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('kl' , 'Kalaallisut')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('km' , 'Central Khmer ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('kn' , 'Kannada ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('ko' , 'Korean ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('kr' , 'Kanuri ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('ks' , 'Kashmiri ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('ku' , 'Kurdish ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('kv' , 'Komi ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('kw' , 'Cornish ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('ky' , 'Kirghiz')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('la' , 'Latin ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('lb' , 'Luxembourgish')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('lg' , 'Ganda ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('li' , 'Limburgan')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('ln' , 'Lingala ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('lo' , 'Lao ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('lt' , 'Lithuanian ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('lu' , 'Luba-Katanga ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('lv' , 'Latvian ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('mg' , 'Malagasy ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('mh' , 'Marshallese ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('mi' , 'Maori ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('mk' , 'Macedonian ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('ml' , 'Malayalam ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('mn' , 'Mongolian ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('mr' , 'Marathi ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('ms' , 'Malay ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('mt' , 'Maltese ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('my' , 'Burmese ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('na' , 'Nauru ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('nb' , 'Bokmål, Norwegian')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('nd' , 'Ndebele, North')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('ne' , 'Nepali ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('ng' , 'Ndonga ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('nl' , 'Dutch')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('nn' , 'Norwegian Nynorsk')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('no' , 'Norwegian ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('nr' , 'Ndebele, South')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('nv' , 'Navajo')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('ny' , 'Chichewa')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('oc' , 'Occitan (\'post 1500\') ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('oj' , 'Ojibwa ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('om' , 'Oromo ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('or' , 'Oriya ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('os' , 'Ossetian')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('pa' , 'Panjabi')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('pi' , 'Pali ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('pl' , 'Polish ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('ps' , 'Pushto')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('pt' , 'Portuguese ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('qu' , 'Quechua ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('rm' , 'Romansh ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('rn' , 'Rundi ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('ro' , 'Romanian')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('ru' , 'Russian ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('rw' , 'Kinyarwanda ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('sa' , 'Sanskrit ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('sc' , 'Sardinian ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('sd' , 'Sindhi ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('se' , 'Northern Sami ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('sg' , 'Sango ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('si' , 'Sinhala')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('sk' , 'Slovak ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('sl' , 'Slovenian ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('sm' , 'Samoan ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('sn' , 'Shona ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('so' , 'Somali ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('sq' , 'Albanian ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('sr' , 'Serbian ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('ss' , 'Swati ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('st' , 'Sotho, Southern ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('su' , 'Sundanese ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('sv' , 'Swedish ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('sw' , 'Swahili ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('ta' , 'Tamil ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('te' , 'Telugu ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('tg' , 'Tajik ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('th' , 'Thai ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('ti' , 'Tigrinya ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('tk' , 'Turkmen ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('tl' , 'Tagalog ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('tn' , 'Tswana ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('to' , 'Tonga (\'Tonga Islands\') ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('tr' , 'Turkish ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('ts' , 'Tsonga ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('tt' , 'Tatar ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('tw' , 'Twi ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('ty' , 'Tahitian ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('ug' , 'Uighur')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('uk' , 'Ukrainian ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('ur' , 'Urdu ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('uz' , 'Uzbek ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('ve' , 'Venda ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('vi' , 'Vietnamese ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('vo' , 'Volapük ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('wa' , 'Walloon ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('wo' , 'Wolof ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('xh' , 'Xhosa ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('yi' , 'Yiddish ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('yo' , 'Yoruba ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('za' , 'Zhuang')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('zh' , 'Chinese ')
INSERT IGNORE INTO Language_Table ('abbr', 'name') VALUES ('zu' , 'Zulu ')